services:
  - type: web
    name: wwgroupmanagement
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    runtime: python
    branch: main
    repo: https://github.com/Thaveshan/wwgroupmanagement
