services:
  - type: web
    name: ww-group-car-tracker
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.11
    envVars:
      - key: FLASK_ENV
        value: production
